python getting_and_processing_corpora/countrymaker.py -country indonesia
python getting_and_processing_corpora/countrymaker.py -country cuba
python getting_and_processing_corpora/countrymaker.py -country slovenia
python getting_and_processing_corpora/countrymaker.py -country malaysia
python getting_and_processing_corpora/countrymaker.py -country philippines
python getting_and_processing_corpora/countrymaker.py -country estonia
python getting_and_processing_corpora/countrymaker.py -country singapore
python getting_and_processing_corpora/countrymaker.py -country rwanda
python getting_and_processing_corpora/countrymaker.py -country haiti
python getting_and_processing_corpora/countrymaker.py -country colombia

