scp  -i "awsstuff/two" data/lens_processed/f* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/a* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/b* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/c* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/d* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/e* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/1* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/2* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/3* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/4* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/5* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/6* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/7* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/8* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
scp  -i "awsstuff/two" data/lens_processed/9* ubuntu@52.33.98.51:/home/ubuntu/data/lens_processed/
